<a href="https://colab.research.google.com/github/Elise643/Wellnamed/blob/main/Unit%205/Unit%205%20Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Unit 5 Project
I found a dataset about names and gender, so I wanted to see if there was any correlation between where a name is in the alphabet and the gender of the person it's most commonly assigned to. This dataset included many uncommon names which only a single or just a few people had, so those have been omitted.

In [1]:
!pip install ucimlrepo
!pip install preliz

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.11/dist-packages (from ucimlrepo) (2025.1.31)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7
Collecting preliz
  Downloading preliz-0.16.0-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: matplotlib>=3.7 in /usr/local/lib/python3.11/dist-packages (from preliz) (3.10.0)
Requirement already satisfied: numba>=0.59 in /usr/local/lib/python3.11/dist-packages (from preliz) (0.60.0)
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.11/dist-packages (from preliz) (2.0.2)
Requirement already satisfied: scipy<1.15,>=1.10 in /usr/local/lib/python3.11/dist-packages (from preliz) (1.14.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (2.8.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.59->preliz) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.7->preliz) (1.17.0)
Downloading preliz-0.16.0-py3-none-any.whl (519 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.1/519.1 kB 3.8 MB/s eta 0:00:00
Installing collected packages: preliz
Successfully installed preliz-0.16.0

In [2]:
from ucimlrepo import fetch_ucirepo

gender_by_name = fetch_ucirepo(id=591)
data = gender_by_name.data.features

data=data.sort_values(by="Name")
data

           Name Gender  Count   Probability
114150        A      M      2  5.473480e-09
112246        A      F      2  5.473480e-09
115618    A'Aff      F      1  2.736740e-09
133954   A'Aron      M      1  2.736740e-09
115619   A'Dele      F      1  2.736740e-09
...         ...    ...    ...           ...
110558   Zyvion      M      5  1.368370e-08
90632     Zyvon      M      7  1.915720e-08
94120   Zyyanna      F      6  1.642040e-08
96225     Zyyon      M      6  1.642040e-08
87147     Zzyzx      M     10  2.736740e-08

[147269 rows x 4 columns]

In [3]:
!pip install preliz

Requirement already satisfied: preliz in /usr/local/lib/python3.11/dist-packages (0.16.0)
Requirement already satisfied: matplotlib>=3.7 in /usr/local/lib/python3.11/dist-packages (from preliz) (3.10.0)
Requirement already satisfied: numba>=0.59 in /usr/local/lib/python3.11/dist-packages (from preliz) (0.60.0)
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.11/dist-packages (from preliz) (2.0.2)
Requirement already satisfied: scipy<1.15,>=1.10 in /usr/local/lib/python3.11/dist-packages (from preliz) (1.14.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7->preliz) (2.8.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.59->preliz) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.7->preliz) (1.17.0)

In [4]:
import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pymc as pm
import preliz as pz
import seaborn as sns
from sklearn import tree

In [5]:
female=data[data['Gender']=='F']
male = data[data['Gender']=='M']

In [31]:
print("The female list is of length "+str(len(female))+" and the male list is of length "+str(len(male))+" which means the female list is "+str(len(female)-len(male))+" rows longer than the male")

sf=female[female['Count']>=5]
sm=male[male['Count']>=5]

The female list is of length 89749 and the male list is of length 57520 which means the female list is 32229 rows longer than the male

In [40]:
sf=sf.sort_values(by='Count')
sf = sf.reset_index(drop=True)
sf[sf['Count']==5][0:100]
#plt.scatter(sm.index,sm['Count'])

           Name Gender  Count   Probability
0        Danuel      F      5  1.368370e-08
1        Tamhra      F      5  1.368370e-08
2       Tamiaya      F      5  1.368370e-08
3       Tamicko      F      5  1.368370e-08
4       Tameera      F      5  1.368370e-08
..          ...    ...    ...           ...
95      Tamyria      F      5  1.368370e-08
96       Armaya      F      5  1.368370e-08
97  Ngozichukwu      F      5  1.368370e-08
98      Tammyra      F      5  1.368370e-08
99       Nevach      F      5  1.368370e-08

[100 rows x 4 columns]

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Count']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Count'}, axis=1)
              .sort_values('Count', ascending=True))
  xs = counted['Count']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_0.sort_values('Count', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Count')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Probability']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Probability'}, axis=1)
              .sort_values('Probability', ascending=True))
  xs = counted['Probability']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_1.sort_values('Probability', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Probability')
_ = plt.ylabel('count()')

Hm. Even omitting the least common names we still have some such as Zzyzx, Aaronjacob, Trevorjames (no, this isn't data error, these people just have two first names stuck together), and countless others (well, 5464 for the males where only 5 people have them and 8869 for the females). Plenty of tragedeigh style names as well.